apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: tuomas-test-spark-worker
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        description: Spark Worker
        template.alpha.openshift.io/wait-for-ready: "true"
      labels:
        app: tuomas-test-spark-worker
    spec:
      volumes:
        - name: tuomas-test-vol
          persistentVolumeClaim:
            claimName: tuomas-test-pvc
      containers:
        - name: spark-worker
          image: docker-registry.rahti.csc.fi/spark-images/spark:2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_WORKER_MEMORY
              value: 4G
            - name: SPARK_WORKER_CORES
              value: '1'
            - name: SPARK_MASTER_SERVICE_HOST
              value: tuomas-test-spark-master
            - name: SPARK_WORKER_DIRS
              value: "/tmp/worker"
            - name: START_COMMAND
              value: "/usr/local/bin/start-worker.sh"
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
                cpu: "1"
                memory: "4G"
            limits:
                cpu: "1"
                memory: "4G"
          volumeMounts:
          - name: tuomas-test-vol
            mountPath: /mnt/tuomas-test-pvc
